export const liveConversationStats = [
  { label: "Live Threads", value: "14" },
  { label: "Needs You", value: "3" },
  { label: "Median Reply", value: "21 s" },
  { label: "Booked Today", value: "6" },
] as const;

export const liveConversationRows = [
  {
    id: "conv-001",
    lead: "Maya Chen",
    source: "Realtor.ca form",
    stage: "Requested",
    stageDot: "bg-sky-400",
    context: "Own listing",
    inquiry: "Showing",
    summary: "Wants to confirm a 6:30 PM showing and add her partner by video.",
    generatedAt: "Realtor.ca form at 2:13 PM",
    leadInput:
      "Can you confirm the 6:30 PM showing and tell me whether my partner can join remotely?",
    journey:
      "Form captured -> Alex replied by SMS -> Maya asked a follow-up about offer timing -> Alex paused for approval.",
    channels: "SMS only",
    responseTime: "18 s",
    exchangeCount: "3 messages",
    agentAction: "Can send SMS, waiting on listing-specific approval",
    lastActivity: "10 sec ago",
    aiOwner: "Alex",
  },
  {
    id: "conv-002",
    lead: "Avery Singh",
    source: "Facebook lead ad",
    stage: "Qualified",
    stageDot: "bg-emerald-400",
    context: "Relocation",
    inquiry: "Buyer",
    summary: "Moving from Calgary in June and already pre-approved.",
    generatedAt: "Facebook instant form at 1:42 PM",
    leadInput:
      "We are relocating from Calgary in June and need a 3-bed near good schools. We are already pre-approved.",
    journey:
      "Lead ad captured -> Alex replied by SMS -> Avery shared budget and timeline -> Alex narrowed neighborhood fit.",
    channels: "SMS only",
    responseTime: "21 s",
    exchangeCount: "4 messages",
    agentAction: "Can keep texting autonomously",
    lastActivity: "45 sec ago",
    aiOwner: "Alex",
  },
  {
    id: "conv-003",
    lead: "Jordan Velasco",
    source: "REW",
    stage: "Qualifying",
    stageDot: "bg-amber-400",
    context: "Other listing",
    inquiry: "Condo",
    summary: "Asked about another brokerage's listing and needs financing help.",
    generatedAt: "REW inquiry at 12:58 PM",
    leadInput:
      "I saw the condo on REW. Is it still available and do you know if the building is lender-friendly?",
    journey:
      "REW inquiry captured -> Alex emailed listing details -> moved the thread to SMS -> financing questions surfaced.",
    channels: "Email + SMS",
    responseTime: "44 s",
    exchangeCount: "5 messages",
    agentAction: "Can send financing follow-up",
    lastActivity: "2 min ago",
    aiOwner: "Alex",
  },
  {
    id: "conv-004",
    lead: "Nina Patel",
    source: "WordPress site",
    stage: "Requested",
    stageDot: "bg-sky-400",
    context: "Seller",
    inquiry: "Townhouse",
    summary: "Wants to know whether spring is the right time to list.",
    generatedAt: "Website form at 11:21 AM",
    leadInput:
      "I own a townhouse in West Springs. Is this spring a good time to list, or should I wait until summer?",
    journey:
      "Site form captured -> Alex replied by email -> Nina asked about timing and pricing -> Alex drafted a valuation response.",
    channels: "Email only",
    responseTime: "1m 12s",
    exchangeCount: "2 messages",
    agentAction: "Can draft seller reply, no SMS yet",
    lastActivity: "6 min ago",
    aiOwner: "Alex",
  },
  {
    id: "conv-005",
    lead: "Eric Thompson",
    source: "RealtyNinja site",
    stage: "Qualified",
    stageDot: "bg-emerald-400",
    context: "Buyer",
    inquiry: "Suite search",
    summary: "Looking under $850k and wants a legal suite.",
    generatedAt: "RealtyNinja form at 10:47 AM",
    leadInput:
      "Looking under $850k and we need a legal suite. Do you have anything in the west end that fits?",
    journey:
      "Site form captured -> Alex replied by SMS -> Eric shared must-haves -> Alex proposed next shortlist step.",
    channels: "SMS only",
    responseTime: "19 s",
    exchangeCount: "4 messages",
    agentAction: "Can send shortlist SMS",
    lastActivity: "8 min ago",
    aiOwner: "Alex",
  },
] as const;

export const selectedConversation = {
  lead: "Maya Chen",
  subtitle: "Oakridge listing showing request",
  messages: [
    {
      speaker: "AI Alex",
      body: "Happy to help. The 6:30 PM slot is still available and I can check whether your partner can join remotely.",
      time: "2:14 PM",
      tone: "bg-emerald-500/10 border-emerald-500/20 text-emerald-100",
    },
    {
      speaker: "Maya",
      body: "Perfect, and if the showing goes well we may want to talk about offer strategy that same night.",
      time: "2:15 PM",
      tone: "bg-background/60 border-border/60 text-foreground",
    },
    {
      speaker: "AI Alex",
      body: "I’ve paused here because this is your own listing and the client is asking to coordinate a more involved handoff.",
      time: "2:16 PM",
      tone: "bg-rose-500/10 border-rose-500/20 text-rose-100",
    },
  ],
  callouts: [
    { label: "Why it matters", value: "Active buyer, asking for same-day showing." },
    { label: "Current blocker", value: "Needs approval to promise remote partner access." },
    { label: "Suggested move", value: "Take over, confirm the showing, and tee up offer guidance." },
  ],
} as const;

export const leadOverviewStats = [
  { label: "Open Leads", value: "28" },
  { label: "Qualified", value: "11" },
  { label: "Need Response", value: "3" },
  { label: "Seller Leads", value: "5" },
] as const;

export const leadsRows = [
  {
    lead: "Maya Chen",
    source: "Realtor.ca",
    stage: "Requested",
    stageDot: "bg-sky-400",
    category: "Own listing",
    approval: "Needs approval",
    location: "Oakridge",
    budget: "N/A",
    updated: "10 sec ago",
  },
  {
    lead: "Avery Singh",
    source: "Facebook lead ad",
    stage: "Qualified",
    stageDot: "bg-emerald-400",
    category: "Relocation buyer",
    approval: "Pre-approved",
    location: "Moving from Calgary",
    budget: "$900k",
    updated: "45 sec ago",
  },
  {
    lead: "Jordan Velasco",
    source: "REW",
    stage: "Qualifying",
    stageDot: "bg-amber-400",
    category: "Other listing",
    approval: "Needs financing help",
    location: "Downtown condo",
    budget: "$650k",
    updated: "2 min ago",
  },
  {
    lead: "Nina Patel",
    source: "WordPress site",
    stage: "Requested",
    stageDot: "bg-sky-400",
    category: "Seller lead",
    approval: "Valuation requested",
    location: "West Springs townhouse",
    budget: "N/A",
    updated: "6 min ago",
  },
  {
    lead: "Eric Thompson",
    source: "RealtyNinja site",
    stage: "Qualified",
    stageDot: "bg-emerald-400",
    category: "Buyer lead",
    approval: "Pre-approved",
    location: "Legal suite search",
    budget: "$850k",
    updated: "8 min ago",
  },
  {
    lead: "Chloe Martin",
    source: "Website form",
    stage: "Needs follow-up",
    stageDot: "bg-rose-400",
    category: "Seller lead",
    approval: "Call requested",
    location: "Altadore detached",
    budget: "N/A",
    updated: "14 min ago",
  },
] as const;

export const performanceStats = [
  { label: "Avg Response", value: "23 s" },
  { label: "Saved This Week", value: "14.3 hrs" },
  { label: "Qualified Rate", value: "8/11" },
  { label: "Calls Booked", value: "6" },
] as const;

export const performanceRows = [
  {
    source: "Realtor.ca",
    leads: 7,
    qualified: 3,
    qualificationRate: "43%",
    avgResponse: "18 s",
    booked: 2,
    sellerLeads: 1,
  },
  {
    source: "Facebook lead ads",
    leads: 9,
    qualified: 4,
    qualificationRate: "44%",
    avgResponse: "21 s",
    booked: 2,
    sellerLeads: 0,
  },
  {
    source: "WordPress site",
    leads: 5,
    qualified: 1,
    qualificationRate: "20%",
    avgResponse: "31 s",
    booked: 1,
    sellerLeads: 3,
  },
  {
    source: "REW",
    leads: 4,
    qualified: 2,
    qualificationRate: "50%",
    avgResponse: "26 s",
    booked: 1,
    sellerLeads: 0,
  },
  {
    source: "RealtyNinja",
    leads: 3,
    qualified: 2,
    qualificationRate: "67%",
    avgResponse: "19 s",
    booked: 0,
    sellerLeads: 0,
  },
] as const;
